[project]
name = "advent-of-code"
version = "0.1.0"
description = "nothing special to see here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
]
